Repository libreoffice-kr/autocorr_kr, pull requests merged in 2020-10, with the labels that each got.

#2 patch README & initial Korean Autocorrect xml file for LibreOffice
  DocumentList.xml
  README.md
Labels: documentation, good first issue

#11 Add Korean Auto Correst list
  DocumentList.xml
Labels: enhancement, hacktoberfest

#12 Add Korean Auto Correst list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#13 Add Korean auto correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#15 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#16 add korean autocorrect list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#26 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#20 Add : Korean Autocorr List
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#31 Add Korean Auto Correction List
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#33 add reminders sections
  README.md
Labels: documentation, enhancement, hacktoberfest, 핵토버페스트

#23 Update DocumentList.xml
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#30 Update DocumentList.xml
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#27 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#37 Add Korean Auto Correct list & README.md 오탈자 수정
  DocumentList.xml
  README.md
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#36 Add : Korean Autocorr List
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#41 Add Korean Auto Correct List
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#44 Add Korean Auto Correct List
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#45 add korean autocorrect list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#48 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#47 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#43 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#50 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#53 add korean autocorrect list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#54 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#52 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#55 add korean autocorrect list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#56 Add Korean Auto Correct list
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트

#57 Update DocumentList.xml
  DocumentList.xml
Labels: enhancement, good first issue, hacktoberfest, 핵토버페스트
